// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwgdxndodtqlepnnghes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3Z2R4bmRvZHRxbGVwbm5naGVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTk3NzQsImV4cCI6MjA3MzM3NTc3NH0.ypMxJiy_B-EXQ6gqGEqs0-WyNTgjJtqyaXLeuaeX3fY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});